/** Trivia bank — 200 unique questions; rooms track used ids across games. */
export const TRIVIA_QUESTIONS = [
  { text: "What is the capital of France?", options: ["London","Paris","Berlin","Madrid"], correctIndex: 1 },
  { text: "Which planet is known as the Red Planet?", options: ["Venus","Mars","Jupiter","Saturn"], correctIndex: 1 },
  { text: "How many continents are there?", options: ["5","6","7","8"], correctIndex: 2 },
  { text: "What gas do plants absorb from the atmosphere?", options: ["Oxygen","Nitrogen","Carbon dioxide","Hydrogen"], correctIndex: 2 },
  { text: "Which ocean is the largest?", options: ["Atlantic","Indian","Arctic","Pacific"], correctIndex: 3 },
  { text: "Who painted the Mona Lisa?", options: ["Van Gogh","Picasso","Da Vinci","Monet"], correctIndex: 2 },
  { text: "What is H2O commonly known as?", options: ["Salt","Water","Hydrogen","Oxygen"], correctIndex: 1 },
  { text: "Which country invented pizza?", options: ["USA","France","Italy","Greece"], correctIndex: 2 },
  { text: "How many sides does a hexagon have?", options: ["5","6","7","8"], correctIndex: 1 },
  { text: "What is the fastest land animal?", options: ["Lion","Cheetah","Horse","Leopard"], correctIndex: 1 },
  { text: "What is the smallest prime number?", options: ["0","1","2","3"], correctIndex: 2 },
  { text: "Which instrument has 88 keys?", options: ["Guitar","Piano","Violin","Flute"], correctIndex: 1 },
  { text: "What is the capital of Japan?", options: ["Seoul","Beijing","Tokyo","Bangkok"], correctIndex: 2 },
  { text: "How many players are on a soccer team on the field?", options: ["9","10","11","12"], correctIndex: 2 },
  { text: "Which metal is liquid at room temperature?", options: ["Gold","Iron","Mercury","Copper"], correctIndex: 2 },
  { text: "What is the largest mammal?", options: ["Elephant","Blue whale","Giraffe","Hippo"], correctIndex: 1 },
  { text: "Which planet is closest to the Sun?", options: ["Venus","Mercury","Earth","Mars"], correctIndex: 1 },
  { text: "What year did the Titanic sink?", options: ["1905","1912","1920","1931"], correctIndex: 1 },
  { text: "What is the chemical symbol for gold?", options: ["Go","Gd","Au","Ag"], correctIndex: 2 },
  { text: "Which country has the kangaroo as a national symbol?", options: ["New Zealand","Australia","South Africa","Canada"], correctIndex: 1 },
  { text: "How many colors are in a rainbow?", options: ["5","6","7","8"], correctIndex: 2 },
  { text: "What is the hardest natural substance?", options: ["Gold","Iron","Diamond","Quartz"], correctIndex: 2 },
  { text: "Which language has the most native speakers?", options: ["English","Spanish","Mandarin Chinese","Hindi"], correctIndex: 2 },
  { text: "What is the capital of Egypt?", options: ["Cairo","Alexandria","Giza","Luxor"], correctIndex: 0 },
  { text: "Which sport uses a shuttlecock?", options: ["Tennis","Badminton","Cricket","Golf"], correctIndex: 1 },
  { text: "What organ pumps blood through the body?", options: ["Lungs","Liver","Heart","Kidney"], correctIndex: 2 },
  { text: "How many days are in a leap year?", options: ["364","365","366","367"], correctIndex: 2 },
  { text: "Which company created the iPhone?", options: ["Samsung","Google","Apple","Microsoft"], correctIndex: 2 },
  { text: "What is the tallest mountain in the world?", options: ["K2","Everest","Kangchenjunga","Lhotse"], correctIndex: 1 },
  { text: "Which gas makes up most of Earth's atmosphere?", options: ["Oxygen","Carbon dioxide","Nitrogen","Argon"], correctIndex: 2 },
  { text: "What is the main ingredient in guacamole?", options: ["Tomato","Avocado","Onion","Pepper"], correctIndex: 1 },
  { text: "Which country is home to the Great Wall?", options: ["Japan","India","China","Mongolia"], correctIndex: 2 },
  { text: "What is 15 × 4?", options: ["45","50","60","65"], correctIndex: 2 },
  { text: "Which bird is a universal symbol of peace?", options: ["Eagle","Dove","Owl","Swan"], correctIndex: 1 },
  { text: "What is the capital of Canada?", options: ["Toronto","Vancouver","Ottawa","Montreal"], correctIndex: 2 },
  { text: "How many bones are in the adult human body?", options: ["186","206","226","256"], correctIndex: 1 },
  { text: "Which planet has the most moons?", options: ["Jupiter","Saturn","Uranus","Neptune"], correctIndex: 1 },
  { text: "What is the largest desert in the world?", options: ["Sahara","Arabian","Antarctic","Gobi"], correctIndex: 2 },
  { text: "Who wrote Romeo and Juliet?", options: ["Dickens","Shakespeare","Austen","Hemingway"], correctIndex: 1 },
  { text: "What is the speed of light approximately (km/s)?", options: ["150,000","200,000","300,000","400,000"], correctIndex: 2 },
  { text: "Which vitamin comes from sunlight?", options: ["Vitamin A","Vitamin C","Vitamin D","Vitamin K"], correctIndex: 2 },
  { text: "What is the capital of Brazil?", options: ["Rio de Janeiro","São Paulo","Brasília","Salvador"], correctIndex: 2 },
  { text: "Which animal is known as the King of the Jungle?", options: ["Tiger","Lion","Bear","Leopard"], correctIndex: 1 },
  { text: "How many minutes are in three hours?", options: ["120","150","180","200"], correctIndex: 2 },
  { text: "What is the boiling point of water (°C)?", options: ["90","100","110","120"], correctIndex: 1 },
  { text: "Which continent is the Sahara Desert on?", options: ["Asia","Africa","Australia","South America"], correctIndex: 1 },
  { text: "What is the largest country by area?", options: ["China","USA","Canada","Russia"], correctIndex: 3 },
  { text: "Which sea creature has three hearts?", options: ["Dolphin","Shark","Octopus","Whale"], correctIndex: 2 },
  { text: "What is the capital of Italy?", options: ["Milan","Venice","Rome","Naples"], correctIndex: 2 },
  { text: "Which element has the chemical symbol 'O'?", options: ["Gold","Osmium","Oxygen","Ozone"], correctIndex: 2 },
  { text: "What is the capital of Spain?", options: ["Barcelona","Madrid","Seville","Valencia"], correctIndex: 1 },
  { text: "Which country is famous for the Taj Mahal?", options: ["Pakistan","India","Bangladesh","Nepal"], correctIndex: 1 },
  { text: "What is the largest island in the world?", options: ["Borneo","Greenland","Madagascar","New Guinea"], correctIndex: 1 },
  { text: "Which river is the longest in the world?", options: ["Amazon","Nile","Yangtze","Mississippi"], correctIndex: 1 },
  { text: "What is the capital of Germany?", options: ["Munich","Hamburg","Berlin","Frankfurt"], correctIndex: 2 },
  { text: "Which US state is known as the Sunshine State?", options: ["Texas","California","Florida","Arizona"], correctIndex: 2 },
  { text: "What is the currency of Japan?", options: ["Won","Yuan","Yen","Ringgit"], correctIndex: 2 },
  { text: "Which mountain range contains Mount Everest?", options: ["Alps","Andes","Himalayas","Rockies"], correctIndex: 2 },
  { text: "What is the capital of South Korea?", options: ["Busan","Seoul","Incheon","Daegu"], correctIndex: 1 },
  { text: "Which African country was formerly called Zaire?", options: ["Kenya","DR Congo","Ghana","Sudan"], correctIndex: 1 },
  { text: "What is the smallest country in the world?", options: ["Monaco","Vatican City","San Marino","Liechtenstein"], correctIndex: 1 },
  { text: "Which strait separates Europe and Africa?", options: ["Bering","Gibraltar","Malacca","Hormuz"], correctIndex: 1 },
  { text: "What is the capital of Mexico?", options: ["Guadalajara","Mexico City","Cancún","Monterrey"], correctIndex: 1 },
  { text: "Which lake is the largest freshwater lake by surface area?", options: ["Michigan","Superior","Victoria","Baikal"], correctIndex: 1 },
  { text: "What is the capital of Argentina?", options: ["Lima","Santiago","Buenos Aires","Bogotá"], correctIndex: 2 },
  { text: "Which country has the most time zones?", options: ["USA","Russia","France","China"], correctIndex: 2 },
  { text: "What is the capital of Turkey?", options: ["Istanbul","Ankara","Izmir","Antalya"], correctIndex: 1 },
  { text: "Which desert covers much of Mongolia and China?", options: ["Sahara","Gobi","Kalahari","Atacama"], correctIndex: 1 },
  { text: "What is the capital of Thailand?", options: ["Phuket","Bangkok","Chiang Mai","Pattaya"], correctIndex: 1 },
  { text: "Which European city is known as the Eternal City?", options: ["Athens","Rome","Paris","Vienna"], correctIndex: 1 },
  { text: "What is the capital of Nigeria?", options: ["Lagos","Abuja","Kano","Ibadan"], correctIndex: 1 },
  { text: "Which country is both in Europe and Asia?", options: ["Egypt","Turkey","Greece","Iran"], correctIndex: 1 },
  { text: "What is the capital of Sweden?", options: ["Oslo","Stockholm","Helsinki","Copenhagen"], correctIndex: 1 },
  { text: "Which US city is nicknamed the Big Apple?", options: ["Los Angeles","Chicago","New York","Boston"], correctIndex: 2 },
  { text: "What is the capital of Portugal?", options: ["Porto","Lisbon","Faro","Braga"], correctIndex: 1 },
  { text: "Which sea is the Dead Sea part of?", options: ["Red Sea","Mediterranean","Jordan Rift","Arabian Sea"], correctIndex: 2 },
  { text: "What is the capital of Poland?", options: ["Kraków","Warsaw","Gdańsk","Wrocław"], correctIndex: 1 },
  { text: "Which country is the Eiffel Tower in?", options: ["Belgium","France","Switzerland","Italy"], correctIndex: 1 },
  { text: "What is the capital of Vietnam?", options: ["Hanoi","Ho Chi Minh City","Da Nang","Hue"], correctIndex: 0 },
  { text: "Which ocean lies east of Africa?", options: ["Atlantic","Indian","Pacific","Southern"], correctIndex: 1 },
  { text: "What is the capital of Greece?", options: ["Thessaloniki","Athens","Crete","Rhodes"], correctIndex: 1 },
  { text: "Which country has the city of Dubai?", options: ["Qatar","UAE","Saudi Arabia","Oman"], correctIndex: 1 },
  { text: "What is the capital of Norway?", options: ["Bergen","Oslo","Trondheim","Stavanger"], correctIndex: 1 },
  { text: "Which waterfall is on the border of Canada and the USA?", options: ["Angel","Niagara","Victoria","Iguazu"], correctIndex: 1 },
  { text: "What is the capital of Chile?", options: ["Lima","Santiago","Quito","La Paz"], correctIndex: 1 },
  { text: "Which country is known as the Land of the Rising Sun?", options: ["China","Japan","Korea","Thailand"], correctIndex: 1 },
  { text: "What is the capital of Indonesia?", options: ["Bali","Jakarta","Surabaya","Medan"], correctIndex: 1 },
  { text: "Which planet is famous for its rings?", options: ["Jupiter","Saturn","Uranus","Neptune"], correctIndex: 1 },
  { text: "What force keeps us on the ground?", options: ["Magnetism","Friction","Gravity","Inertia"], correctIndex: 2 },
  { text: "What is the center of an atom called?", options: ["Electron","Proton","Nucleus","Neutron"], correctIndex: 2 },
  { text: "Which blood type is known as the universal donor?", options: ["A+","B+","AB+","O-"], correctIndex: 3 },
  { text: "What part of the cell contains genetic material?", options: ["Ribosome","Nucleus","Membrane","Cytoplasm"], correctIndex: 1 },
  { text: "Which planet is the largest in our solar system?", options: ["Saturn","Jupiter","Neptune","Uranus"], correctIndex: 1 },
  { text: "What is the chemical formula for table salt?", options: ["NaCl","KCl","CaCO3","H2SO4"], correctIndex: 0 },
  { text: "Which scientist developed the theory of relativity?", options: ["Newton","Einstein","Tesla","Galileo"], correctIndex: 1 },
  { text: "What is the main gas humans exhale?", options: ["Oxygen","Nitrogen","Carbon dioxide","Hydrogen"], correctIndex: 2 },
  { text: "Which organ filters blood in the human body?", options: ["Heart","Liver","Kidney","Stomach"], correctIndex: 2 },
  { text: "What is the freezing point of water (°C)?", options: ["-10","0","10","32"], correctIndex: 1 },
  { text: "Which particle has a negative charge?", options: ["Proton","Neutron","Electron","Photon"], correctIndex: 2 },
  { text: "What is the powerhouse of the cell?", options: ["Nucleus","Mitochondria","Ribosome","Golgi"], correctIndex: 1 },
  { text: "Which metal is most abundant in Earth's crust?", options: ["Iron","Copper","Aluminum","Gold"], correctIndex: 2 },
  { text: "What type of animal is a dolphin?", options: ["Fish","Mammal","Reptile","Amphibian"], correctIndex: 1 },
  { text: "Which vitamin is found in citrus fruits?", options: ["Vitamin A","Vitamin B","Vitamin C","Vitamin D"], correctIndex: 2 },
  { text: "What is the study of earthquakes called?", options: ["Geology","Seismology","Meteorology","Ecology"], correctIndex: 1 },
  { text: "Which gas do humans need to breathe?", options: ["Carbon dioxide","Oxygen","Helium","Nitrogen"], correctIndex: 1 },
  { text: "What is the nearest star to Earth?", options: ["Proxima Centauri","Sirius","The Sun","Alpha Centauri"], correctIndex: 2 },
  { text: "Which bones protect the brain?", options: ["Ribs","Skull","Pelvis","Spine"], correctIndex: 1 },
  { text: "What is the chemical symbol for iron?", options: ["Ir","In","Fe","I"], correctIndex: 2 },
  { text: "Which layer of Earth do we live on?", options: ["Core","Mantle","Crust","Magma"], correctIndex: 2 },
  { text: "What is the largest internal organ in the human body?", options: ["Heart","Liver","Lung","Brain"], correctIndex: 1 },
  { text: "Which planet is known as Earth's twin?", options: ["Mars","Venus","Mercury","Neptune"], correctIndex: 1 },
  { text: "What is the process plants use to make food?", options: ["Respiration","Photosynthesis","Digestion","Fermentation"], correctIndex: 1 },
  { text: "Which acid is found in the stomach?", options: ["Sulfuric","Hydrochloric","Nitric","Acetic"], correctIndex: 1 },
  { text: "What is the unit of electric current?", options: ["Volt","Watt","Ampere","Ohm"], correctIndex: 2 },
  { text: "Which animal lays the largest eggs?", options: ["Crocodile","Ostrich","Emu","Chicken"], correctIndex: 1 },
  { text: "What is the chemical symbol for sodium?", options: ["So","Sd","Na","S"], correctIndex: 2 },
  { text: "Which planet takes about 365 days to orbit the Sun?", options: ["Mars","Earth","Venus","Mercury"], correctIndex: 1 },
  { text: "What is the hardest bone in the human body?", options: ["Femur","Skull","Rib","Spine"], correctIndex: 0 },
  { text: "Which instrument measures temperature?", options: ["Barometer","Thermometer","Hygrometer","Altimeter"], correctIndex: 1 },
  { text: "What is the main component of the Sun?", options: ["Helium","Hydrogen","Oxygen","Carbon"], correctIndex: 1 },
  { text: "Which blood cells fight infection?", options: ["Red","White","Platelets","Plasma"], correctIndex: 1 },
  { text: "What is the chemical symbol for carbon?", options: ["Ca","Co","C","Cr"], correctIndex: 2 },
  { text: "Which scientist proposed the laws of motion?", options: ["Darwin","Newton","Faraday","Pasteur"], correctIndex: 1 },
  { text: "What is the largest species of bear?", options: ["Grizzly","Polar bear","Panda","Black bear"], correctIndex: 1 },
  { text: "Which organ produces insulin?", options: ["Liver","Pancreas","Kidney","Spleen"], correctIndex: 1 },
  { text: "What is the chemical symbol for silver?", options: ["Si","Sv","Ag","Au"], correctIndex: 2 },
  { text: "Which planet is farthest from the Sun?", options: ["Uranus","Neptune","Pluto","Saturn"], correctIndex: 1 },
  { text: "What is the study of living things called?", options: ["Physics","Biology","Chemistry","Geology"], correctIndex: 1 },
  { text: "Which part of the eye controls light entry?", options: ["Retina","Iris","Cornea","Lens"], correctIndex: 1 },
  { text: "What is the chemical symbol for potassium?", options: ["P","Po","K","Pt"], correctIndex: 2 },
  { text: "Which animal is the largest living reptile?", options: ["Komodo dragon","Saltwater crocodile","Anaconda","Alligator"], correctIndex: 1 },
  { text: "What is the most abundant element in the universe?", options: ["Oxygen","Carbon","Hydrogen","Helium"], correctIndex: 2 },
  { text: "Which war ended in 1945?", options: ["World War I","World War II","Korean War","Vietnam War"], correctIndex: 1 },
  { text: "Who was the first President of the United States?", options: ["Lincoln","Washington","Jefferson","Adams"], correctIndex: 1 },
  { text: "In which year did India gain independence?", options: ["1945","1947","1950","1960"], correctIndex: 1 },
  { text: "Who discovered penicillin?", options: ["Pasteur","Fleming","Curie","Jenner"], correctIndex: 1 },
  { text: "Which ancient civilization built the pyramids?", options: ["Romans","Greeks","Egyptians","Mayans"], correctIndex: 2 },
  { text: "Who was known as the Maid of Orléans?", options: ["Marie Curie","Joan of Arc","Cleopatra","Elizabeth I"], correctIndex: 1 },
  { text: "Which empire was ruled by Julius Caesar?", options: ["Greek","Roman","Ottoman","Persian"], correctIndex: 1 },
  { text: "In which year did the Berlin Wall fall?", options: ["1987","1989","1991","1993"], correctIndex: 1 },
  { text: "Who painted the ceiling of the Sistine Chapel?", options: ["Raphael","Michelangelo","Donatello","Botticelli"], correctIndex: 1 },
  { text: "Which ship carried the Pilgrims to America in 1620?", options: ["Santa Maria","Mayflower","Victory","Endeavour"], correctIndex: 1 },
  { text: "Who wrote '1984'?", options: ["Orwell","Huxley","Bradbury","Asimov"], correctIndex: 0 },
  { text: "Which civilization used hieroglyphics?", options: ["Roman","Egyptian","Chinese","Incan"], correctIndex: 1 },
  { text: "Who was the first man on the Moon?", options: ["Aldrin","Armstrong","Collins","Gagarin"], correctIndex: 1 },
  { text: "Which country was formerly known as Persia?", options: ["Iraq","Iran","Syria","Turkey"], correctIndex: 1 },
  { text: "Who invented the telephone?", options: ["Edison","Bell","Marconi","Tesla"], correctIndex: 1 },
  { text: "Which empire built Machu Picchu?", options: ["Aztec","Inca","Maya","Olmec"], correctIndex: 1 },
  { text: "In which year did the French Revolution begin?", options: ["1776","1789","1804","1815"], correctIndex: 1 },
  { text: "Who was the British Prime Minister during most of WWII?", options: ["Chamberlain","Churchill","Attlee","Eden"], correctIndex: 1 },
  { text: "Which document began with 'We the People'?", options: ["Bill of Rights","US Constitution","Declaration","Magna Carta"], correctIndex: 1 },
  { text: "Who discovered gravity after seeing a falling apple?", options: ["Galileo","Newton","Kepler","Copernicus"], correctIndex: 1 },
  { text: "Which ancient wonder was in Babylon?", options: ["Colossus","Hanging Gardens","Lighthouse","Mausoleum"], correctIndex: 1 },
  { text: "Who was the first woman to win a Nobel Prize?", options: ["Curie","Franklin","Hopper","Nightingale"], correctIndex: 0 },
  { text: "Which country gifted the Statue of Liberty to the USA?", options: ["UK","France","Spain","Italy"], correctIndex: 1 },
  { text: "Who led the nonviolent movement in India?", options: ["Nehru","Gandhi","Patel","Bose"], correctIndex: 1 },
  { text: "Which war was fought between the North and South in the USA?", options: ["Revolutionary","Civil War","Spanish-American","Mexican"], correctIndex: 1 },
  { text: "Who wrote 'The Odyssey'?", options: ["Virgil","Homer","Sophocles","Plato"], correctIndex: 1 },
  { text: "Which pharaoh's tomb was found in 1922?", options: ["Ramses","Tutankhamun","Khufu","Akhenaten"], correctIndex: 1 },
  { text: "Who invented the printing press?", options: ["Gutenberg","Franklin","Edison","Watt"], correctIndex: 0 },
  { text: "Which city was divided by a wall until 1989?", options: ["Vienna","Berlin","Prague","Warsaw"], correctIndex: 1 },
  { text: "Who was the longest-reigning British monarch before Charles III?", options: ["Victoria","Elizabeth II","George III","Henry VIII"], correctIndex: 1 },
  { text: "Which explorer sailed to the Americas in 1492?", options: ["Magellan","Columbus","Cook","Drake"], correctIndex: 1 },
  { text: "Who painted 'Starry Night'?", options: ["Monet","Van Gogh","Picasso","Rembrandt"], correctIndex: 1 },
  { text: "Which ancient Greek city-state was known for warriors?", options: ["Athens","Sparta","Corinth","Thebes"], correctIndex: 1 },
  { text: "Who was assassinated in Dallas in 1963?", options: ["Kennedy","King","Lincoln","Garfield"], correctIndex: 0 },
  { text: "Which revolution began in Russia in 1917?", options: ["1905 Revolution","February Revolution","October Revolution","Both Feb and Oct"], correctIndex: 3 },
  { text: "How many players on a basketball team on court?", options: ["4","5","6","7"], correctIndex: 1 },
  { text: "Which country won the first FIFA World Cup in 1930?", options: ["Brazil","Uruguay","Italy","Argentina"], correctIndex: 1 },
  { text: "In tennis, what is a score of zero called?", options: ["Nil","Love","Blank","Zero"], correctIndex: 1 },
  { text: "How many rings are on the Olympic flag?", options: ["4","5","6","7"], correctIndex: 1 },
  { text: "Which sport is played at Wimbledon?", options: ["Golf","Tennis","Cricket","Rugby"], correctIndex: 1 },
  { text: "What is the maximum score in a single dart throw?", options: ["50","60","100","180"], correctIndex: 1 },
  { text: "Which country hosts the Tour de France?", options: ["Spain","Italy","France","Belgium"], correctIndex: 2 },
  { text: "How many bases are on a baseball diamond?", options: ["3","4","5","6"], correctIndex: 1 },
  { text: "Which sport uses a puck?", options: ["Soccer","Hockey","Lacrosse","Polo"], correctIndex: 1 },
  { text: "What color jersey does the Tour de France leader wear?", options: ["Green","Polka dot","Yellow","White"], correctIndex: 2 },
  { text: "How long is a marathon in miles (approx)?", options: ["20.2","24.2","26.2","28.2"], correctIndex: 2 },
  { text: "Which sport is associated with the Super Bowl?", options: ["Baseball","American football","Basketball","Hockey"], correctIndex: 1 },
  { text: "How many holes are played in a standard golf round?", options: ["9","12","18","24"], correctIndex: 2 },
  { text: "Which country invented cricket?", options: ["Australia","England","India","South Africa"], correctIndex: 1 },
  { text: "What is the national sport of Canada?", options: ["Hockey","Lacrosse","Curling","Skiing"], correctIndex: 1 },
  { text: "How many points is a touchdown worth in NFL?", options: ["3","6","7","8"], correctIndex: 1 },
  { text: "Which sport uses a net but no racket?", options: ["Tennis","Volleyball","Squash","Badminton"], correctIndex: 1 },
  { text: "Who has won the most Formula 1 world titles (as of 2023)?", options: ["Hamilton","Schumacher","Verstappen","Prost"], correctIndex: 1 },
  { text: "Which ball sport is played at the Masters?", options: ["Tennis","Golf","Cricket","Rugby"], correctIndex: 1 },
  { text: "How many periods in a standard ice hockey game?", options: ["2","3","4","5"], correctIndex: 1 },
  { text: "Which country won the 2018 FIFA World Cup?", options: ["Germany","France","Brazil","Argentina"], correctIndex: 1 },
  { text: "What is a strike in bowling?", options: ["5 pins","All 10 pins","7 pins","Split"], correctIndex: 1 },
  { text: "Who directed 'Jurassic Park'?", options: ["Spielberg","Cameron","Nolan","Scott"], correctIndex: 0 },
  { text: "Which movie features the character Iron Man?", options: ["DC Universe","Marvel","Star Wars","Matrix"], correctIndex: 1 },
  { text: "Who played Jack in 'Titanic'?", options: ["Pitt","DiCaprio","Cruise","Depp"], correctIndex: 1 },
  { text: "Which series features Hogwarts School?", options: ["Narnia","Harry Potter","Lord of the Rings","Percy Jackson"], correctIndex: 1 },
  { text: "What is the highest-grossing film franchise?", options: ["Star Wars","Marvel","Harry Potter","Bond"], correctIndex: 1 },
  { text: "Who sang 'Thriller'?", options: ["Prince","Michael Jackson","Madonna","Elvis"], correctIndex: 1 },
  { text: "Which instrument did Jimi Hendrix play?", options: ["Piano","Guitar","Drums","Saxophone"], correctIndex: 1 },
  { text: "What is the name of the lion in 'The Lion King'?", options: ["Mufasa","Simba","Scar","Nala"], correctIndex: 1 },
  { text: "Who created Mickey Mouse?", options: ["Warner","Disney","Hanna-Barbera","Pixar"], correctIndex: 1 },
  { text: "Which band performed 'Bohemian Rhapsody'?", options: ["Beatles","Queen","Led Zeppelin","Pink Floyd"], correctIndex: 1 },
  { text: "What is the wizard's name in 'The Lord of the Rings'?", options: ["Merlin","Gandalf","Dumbledore","Saruman"], correctIndex: 1 },
];
