import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const raw = [
  ["What is the capital of France?", ["London", "Paris", "Berlin", "Madrid"], 1],
  ["Which planet is known as the Red Planet?", ["Venus", "Mars", "Jupiter", "Saturn"], 1],
  ["How many continents are there?", ["5", "6", "7", "8"], 2],
  ["What gas do plants absorb from the atmosphere?", ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], 2],
  ["Which ocean is the largest?", ["Atlantic", "Indian", "Arctic", "Pacific"], 3],
  ["Who painted the Mona Lisa?", ["Van Gogh", "Picasso", "Da Vinci", "Monet"], 2],
  ["What is H2O commonly known as?", ["Salt", "Water", "Hydrogen", "Oxygen"], 1],
  ["Which country invented pizza?", ["USA", "France", "Italy", "Greece"], 2],
  ["How many sides does a hexagon have?", ["5", "6", "7", "8"], 1],
  ["What is the fastest land animal?", ["Lion", "Cheetah", "Horse", "Leopard"], 1],
  ["What is the smallest prime number?", ["0", "1", "2", "3"], 2],
  ["Which instrument has 88 keys?", ["Guitar", "Piano", "Violin", "Flute"], 1],
  ["What is the capital of Japan?", ["Seoul", "Beijing", "Tokyo", "Bangkok"], 2],
  ["How many players are on a soccer team on the field?", ["9", "10", "11", "12"], 2],
  ["Which metal is liquid at room temperature?", ["Gold", "Iron", "Mercury", "Copper"], 2],
  ["What is the largest mammal?", ["Elephant", "Blue whale", "Giraffe", "Hippo"], 1],
  ["Which planet is closest to the Sun?", ["Venus", "Mercury", "Earth", "Mars"], 1],
  ["What year did the Titanic sink?", ["1905", "1912", "1920", "1931"], 1],
  ["What is the chemical symbol for gold?", ["Go", "Gd", "Au", "Ag"], 2],
  ["Which country has the kangaroo as a national symbol?", ["New Zealand", "Australia", "South Africa", "Canada"], 1],
  ["How many colors are in a rainbow?", ["5", "6", "7", "8"], 2],
  ["What is the hardest natural substance?", ["Gold", "Iron", "Diamond", "Quartz"], 2],
  ["Which language has the most native speakers?", ["English", "Spanish", "Mandarin Chinese", "Hindi"], 2],
  ["What is the capital of Egypt?", ["Cairo", "Alexandria", "Giza", "Luxor"], 0],
  ["Which sport uses a shuttlecock?", ["Tennis", "Badminton", "Cricket", "Golf"], 1],
  ["What organ pumps blood through the body?", ["Lungs", "Liver", "Heart", "Kidney"], 2],
  ["How many days are in a leap year?", ["364", "365", "366", "367"], 2],
  ["Which company created the iPhone?", ["Samsung", "Google", "Apple", "Microsoft"], 2],
  ["What is the tallest mountain in the world?", ["K2", "Everest", "Kangchenjunga", "Lhotse"], 1],
  ["Which gas makes up most of Earth's atmosphere?", ["Oxygen", "Carbon dioxide", "Nitrogen", "Argon"], 2],
  ["What is the main ingredient in guacamole?", ["Tomato", "Avocado", "Onion", "Pepper"], 1],
  ["Which country is home to the Great Wall?", ["Japan", "India", "China", "Mongolia"], 2],
  ["What is 15 × 4?", ["45", "50", "60", "65"], 2],
  ["Which bird is a universal symbol of peace?", ["Eagle", "Dove", "Owl", "Swan"], 1],
  ["What is the capital of Canada?", ["Toronto", "Vancouver", "Ottawa", "Montreal"], 2],
  ["How many bones are in the adult human body?", ["186", "206", "226", "256"], 1],
  ["Which planet has the most moons?", ["Jupiter", "Saturn", "Uranus", "Neptune"], 1],
  ["What is the largest desert in the world?", ["Sahara", "Arabian", "Antarctic", "Gobi"], 2],
  ["Who wrote Romeo and Juliet?", ["Dickens", "Shakespeare", "Austen", "Hemingway"], 1],
  ["What is the speed of light approximately (km/s)?", ["150,000", "200,000", "300,000", "400,000"], 2],
  ["Which vitamin comes from sunlight?", ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K"], 2],
  ["What is the capital of Brazil?", ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"], 2],
  ["Which animal is known as the King of the Jungle?", ["Tiger", "Lion", "Bear", "Leopard"], 1],
  ["How many minutes are in three hours?", ["120", "150", "180", "200"], 2],
  ["What is the boiling point of water (°C)?", ["90", "100", "110", "120"], 1],
  ["Which continent is the Sahara Desert on?", ["Asia", "Africa", "Australia", "South America"], 1],
  ["What is the largest country by area?", ["China", "USA", "Canada", "Russia"], 3],
  ["Which sea creature has three hearts?", ["Dolphin", "Shark", "Octopus", "Whale"], 2],
  ["What is the capital of Italy?", ["Milan", "Venice", "Rome", "Naples"], 2],
  ["Which element has the chemical symbol 'O'?", ["Gold", "Osmium", "Oxygen", "Ozone"], 2],
  ["What is the capital of Spain?", ["Barcelona", "Madrid", "Seville", "Valencia"], 1],
  ["Which country is famous for the Taj Mahal?", ["Pakistan", "India", "Bangladesh", "Nepal"], 1],
  ["What is the largest island in the world?", ["Borneo", "Greenland", "Madagascar", "New Guinea"], 1],
  ["Which river is the longest in the world?", ["Amazon", "Nile", "Yangtze", "Mississippi"], 1],
  ["What is the capital of Germany?", ["Munich", "Hamburg", "Berlin", "Frankfurt"], 2],
  ["Which US state is known as the Sunshine State?", ["Texas", "California", "Florida", "Arizona"], 2],
  ["What is the currency of Japan?", ["Won", "Yuan", "Yen", "Ringgit"], 2],
  ["Which mountain range contains Mount Everest?", ["Alps", "Andes", "Himalayas", "Rockies"], 2],
  ["What is the capital of South Korea?", ["Busan", "Seoul", "Incheon", "Daegu"], 1],
  ["Which African country was formerly called Zaire?", ["Kenya", "DR Congo", "Ghana", "Sudan"], 1],
  ["What is the smallest country in the world?", ["Monaco", "Vatican City", "San Marino", "Liechtenstein"], 1],
  ["Which strait separates Europe and Africa?", ["Bering", "Gibraltar", "Malacca", "Hormuz"], 1],
  ["What is the capital of Mexico?", ["Guadalajara", "Mexico City", "Cancún", "Monterrey"], 1],
  ["Which lake is the largest freshwater lake by surface area?", ["Michigan", "Superior", "Victoria", "Baikal"], 1],
  ["What is the capital of Argentina?", ["Lima", "Santiago", "Buenos Aires", "Bogotá"], 2],
  ["Which country has the most time zones?", ["USA", "Russia", "France", "China"], 2],
  ["What is the capital of Turkey?", ["Istanbul", "Ankara", "Izmir", "Antalya"], 1],
  ["Which desert covers much of Mongolia and China?", ["Sahara", "Gobi", "Kalahari", "Atacama"], 1],
  ["What is the capital of Thailand?", ["Phuket", "Bangkok", "Chiang Mai", "Pattaya"], 1],
  ["Which European city is known as the Eternal City?", ["Athens", "Rome", "Paris", "Vienna"], 1],
  ["What is the capital of Nigeria?", ["Lagos", "Abuja", "Kano", "Ibadan"], 1],
  ["Which country is both in Europe and Asia?", ["Egypt", "Turkey", "Greece", "Iran"], 1],
  ["What is the capital of Sweden?", ["Oslo", "Stockholm", "Helsinki", "Copenhagen"], 1],
  ["Which US city is nicknamed the Big Apple?", ["Los Angeles", "Chicago", "New York", "Boston"], 2],
  ["What is the capital of Portugal?", ["Porto", "Lisbon", "Faro", "Braga"], 1],
  ["Which sea is the Dead Sea part of?", ["Red Sea", "Mediterranean", "Jordan Rift", "Arabian Sea"], 2],
  ["What is the capital of Poland?", ["Kraków", "Warsaw", "Gdańsk", "Wrocław"], 1],
  ["Which country is the Eiffel Tower in?", ["Belgium", "France", "Switzerland", "Italy"], 1],
  ["What is the capital of Vietnam?", ["Hanoi", "Ho Chi Minh City", "Da Nang", "Hue"], 0],
  ["Which ocean lies east of Africa?", ["Atlantic", "Indian", "Pacific", "Southern"], 1],
  ["What is the capital of Greece?", ["Thessaloniki", "Athens", "Crete", "Rhodes"], 1],
  ["Which country has the city of Dubai?", ["Qatar", "UAE", "Saudi Arabia", "Oman"], 1],
  ["What is the capital of Norway?", ["Bergen", "Oslo", "Trondheim", "Stavanger"], 1],
  ["Which waterfall is on the border of Canada and the USA?", ["Angel", "Niagara", "Victoria", "Iguazu"], 1],
  ["What is the capital of Chile?", ["Lima", "Santiago", "Quito", "La Paz"], 1],
  ["Which country is known as the Land of the Rising Sun?", ["China", "Japan", "Korea", "Thailand"], 1],
  ["What is the capital of Indonesia?", ["Bali", "Jakarta", "Surabaya", "Medan"], 1],
  ["Which planet is famous for its rings?", ["Jupiter", "Saturn", "Uranus", "Neptune"], 1],
  ["What force keeps us on the ground?", ["Magnetism", "Friction", "Gravity", "Inertia"], 2],
  ["What is the center of an atom called?", ["Electron", "Proton", "Nucleus", "Neutron"], 2],
  ["Which blood type is known as the universal donor?", ["A+", "B+", "AB+", "O-"], 3],
  ["What part of the cell contains genetic material?", ["Ribosome", "Nucleus", "Membrane", "Cytoplasm"], 1],
  ["Which planet is the largest in our solar system?", ["Saturn", "Jupiter", "Neptune", "Uranus"], 1],
  ["What is the chemical formula for table salt?", ["NaCl", "KCl", "CaCO3", "H2SO4"], 0],
  ["Which scientist developed the theory of relativity?", ["Newton", "Einstein", "Tesla", "Galileo"], 1],
  ["What is the main gas humans exhale?", ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], 2],
  ["Which organ filters blood in the human body?", ["Heart", "Liver", "Kidney", "Stomach"], 2],
  ["What is the freezing point of water (°C)?", ["-10", "0", "10", "32"], 1],
  ["Which particle has a negative charge?", ["Proton", "Neutron", "Electron", "Photon"], 2],
  ["What is the powerhouse of the cell?", ["Nucleus", "Mitochondria", "Ribosome", "Golgi"], 1],
  ["Which metal is most abundant in Earth's crust?", ["Iron", "Copper", "Aluminum", "Gold"], 2],
  ["What type of animal is a dolphin?", ["Fish", "Mammal", "Reptile", "Amphibian"], 1],
  ["Which vitamin is found in citrus fruits?", ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"], 2],
  ["What is the study of earthquakes called?", ["Geology", "Seismology", "Meteorology", "Ecology"], 1],
  ["Which gas do humans need to breathe?", ["Carbon dioxide", "Oxygen", "Helium", "Nitrogen"], 1],
  ["What is the nearest star to Earth?", ["Proxima Centauri", "Sirius", "The Sun", "Alpha Centauri"], 2],
  ["Which bones protect the brain?", ["Ribs", "Skull", "Pelvis", "Spine"], 1],
  ["What is the chemical symbol for iron?", ["Ir", "In", "Fe", "I"], 2],
  ["Which layer of Earth do we live on?", ["Core", "Mantle", "Crust", "Magma"], 2],
  ["What is the largest internal organ in the human body?", ["Heart", "Liver", "Lung", "Brain"], 1],
  ["Which planet is known as Earth's twin?", ["Mars", "Venus", "Mercury", "Neptune"], 1],
  ["What is the process plants use to make food?", ["Respiration", "Photosynthesis", "Digestion", "Fermentation"], 1],
  ["Which acid is found in the stomach?", ["Sulfuric", "Hydrochloric", "Nitric", "Acetic"], 1],
  ["What is the unit of electric current?", ["Volt", "Watt", "Ampere", "Ohm"], 2],
  ["Which animal lays the largest eggs?", ["Crocodile", "Ostrich", "Emu", "Chicken"], 1],
  ["What is the chemical symbol for sodium?", ["So", "Sd", "Na", "S"], 2],
  ["Which planet takes about 365 days to orbit the Sun?", ["Mars", "Earth", "Venus", "Mercury"], 1],
  ["What is the hardest bone in the human body?", ["Femur", "Skull", "Rib", "Spine"], 0],
  ["Which instrument measures temperature?", ["Barometer", "Thermometer", "Hygrometer", "Altimeter"], 1],
  ["What is the main component of the Sun?", ["Helium", "Hydrogen", "Oxygen", "Carbon"], 1],
  ["Which blood cells fight infection?", ["Red", "White", "Platelets", "Plasma"], 1],
  ["What is the chemical symbol for carbon?", ["Ca", "Co", "C", "Cr"], 2],
  ["Which scientist proposed the laws of motion?", ["Darwin", "Newton", "Faraday", "Pasteur"], 1],
  ["What is the largest species of bear?", ["Grizzly", "Polar bear", "Panda", "Black bear"], 1],
  ["Which organ produces insulin?", ["Liver", "Pancreas", "Kidney", "Spleen"], 1],
  ["What is the chemical symbol for silver?", ["Si", "Sv", "Ag", "Au"], 2],
  ["Which planet is farthest from the Sun?", ["Uranus", "Neptune", "Pluto", "Saturn"], 1],
  ["What is the study of living things called?", ["Physics", "Biology", "Chemistry", "Geology"], 1],
  ["Which part of the eye controls light entry?", ["Retina", "Iris", "Cornea", "Lens"], 1],
  ["What is the chemical symbol for potassium?", ["P", "Po", "K", "Pt"], 2],
  ["Which animal is the largest living reptile?", ["Komodo dragon", "Saltwater crocodile", "Anaconda", "Alligator"], 1],
  ["What is the most abundant element in the universe?", ["Oxygen", "Carbon", "Hydrogen", "Helium"], 2],
  ["Which war ended in 1945?", ["World War I", "World War II", "Korean War", "Vietnam War"], 1],
  ["Who was the first President of the United States?", ["Lincoln", "Washington", "Jefferson", "Adams"], 1],
  ["In which year did India gain independence?", ["1945", "1947", "1950", "1960"], 1],
  ["Who discovered penicillin?", ["Pasteur", "Fleming", "Curie", "Jenner"], 1],
  ["Which ancient civilization built the pyramids?", ["Romans", "Greeks", "Egyptians", "Mayans"], 2],
  ["Who was known as the Maid of Orléans?", ["Marie Curie", "Joan of Arc", "Cleopatra", "Elizabeth I"], 1],
  ["Which empire was ruled by Julius Caesar?", ["Greek", "Roman", "Ottoman", "Persian"], 1],
  ["In which year did the Berlin Wall fall?", ["1987", "1989", "1991", "1993"], 1],
  ["Who painted the ceiling of the Sistine Chapel?", ["Raphael", "Michelangelo", "Donatello", "Botticelli"], 1],
  ["Which ship carried the Pilgrims to America in 1620?", ["Santa Maria", "Mayflower", "Victory", "Endeavour"], 1],
  ["Who wrote '1984'?", ["Orwell", "Huxley", "Bradbury", "Asimov"], 0],
  ["Which civilization used hieroglyphics?", ["Roman", "Egyptian", "Chinese", "Incan"], 1],
  ["Who was the first man on the Moon?", ["Aldrin", "Armstrong", "Collins", "Gagarin"], 1],
  ["Which country was formerly known as Persia?", ["Iraq", "Iran", "Syria", "Turkey"], 1],
  ["Who invented the telephone?", ["Edison", "Bell", "Marconi", "Tesla"], 1],
  ["Which empire built Machu Picchu?", ["Aztec", "Inca", "Maya", "Olmec"], 1],
  ["In which year did the French Revolution begin?", ["1776", "1789", "1804", "1815"], 1],
  ["Who was the British Prime Minister during most of WWII?", ["Chamberlain", "Churchill", "Attlee", "Eden"], 1],
  ["Which document began with 'We the People'?", ["Bill of Rights", "US Constitution", "Declaration", "Magna Carta"], 1],
  ["Who discovered gravity after seeing a falling apple?", ["Galileo", "Newton", "Kepler", "Copernicus"], 1],
  ["Which ancient wonder was in Babylon?", ["Colossus", "Hanging Gardens", "Lighthouse", "Mausoleum"], 1],
  ["Who was the first woman to win a Nobel Prize?", ["Curie", "Franklin", "Hopper", "Nightingale"], 0],
  ["Which country gifted the Statue of Liberty to the USA?", ["UK", "France", "Spain", "Italy"], 1],
  ["Who led the nonviolent movement in India?", ["Nehru", "Gandhi", "Patel", "Bose"], 1],
  ["Which war was fought between the North and South in the USA?", ["Revolutionary", "Civil War", "Spanish-American", "Mexican"], 1],
  ["Who wrote 'The Odyssey'?", ["Virgil", "Homer", "Sophocles", "Plato"], 1],
  ["Which pharaoh's tomb was found in 1922?", ["Ramses", "Tutankhamun", "Khufu", "Akhenaten"], 1],
  ["Who invented the printing press?", ["Gutenberg", "Franklin", "Edison", "Watt"], 0],
  ["Which city was divided by a wall until 1989?", ["Vienna", "Berlin", "Prague", "Warsaw"], 1],
  ["Who was the longest-reigning British monarch before Charles III?", ["Victoria", "Elizabeth II", "George III", "Henry VIII"], 1],
  ["Which explorer sailed to the Americas in 1492?", ["Magellan", "Columbus", "Cook", "Drake"], 1],
  ["Who painted 'Starry Night'?", ["Monet", "Van Gogh", "Picasso", "Rembrandt"], 1],
  ["Which ancient Greek city-state was known for warriors?", ["Athens", "Sparta", "Corinth", "Thebes"], 1],
  ["Who was assassinated in Dallas in 1963?", ["Kennedy", "King", "Lincoln", "Garfield"], 0],
  ["Which revolution began in Russia in 1917?", ["1905 Revolution", "February Revolution", "October Revolution", "Both Feb and Oct"], 3],
  ["How many players on a basketball team on court?", ["4", "5", "6", "7"], 1],
  ["Which country won the first FIFA World Cup in 1930?", ["Brazil", "Uruguay", "Italy", "Argentina"], 1],
  ["In tennis, what is a score of zero called?", ["Nil", "Love", "Blank", "Zero"], 1],
  ["How many rings are on the Olympic flag?", ["4", "5", "6", "7"], 1],
  ["Which sport is played at Wimbledon?", ["Golf", "Tennis", "Cricket", "Rugby"], 1],
  ["What is the maximum score in a single dart throw?", ["50", "60", "100", "180"], 1],
  ["Which country hosts the Tour de France?", ["Spain", "Italy", "France", "Belgium"], 2],
  ["How many bases are on a baseball diamond?", ["3", "4", "5", "6"], 1],
  ["Which sport uses a puck?", ["Soccer", "Hockey", "Lacrosse", "Polo"], 1],
  ["What color jersey does the Tour de France leader wear?", ["Green", "Polka dot", "Yellow", "White"], 2],
  ["How long is a marathon in miles (approx)?", ["20.2", "24.2", "26.2", "28.2"], 2],
  ["Which sport is associated with the Super Bowl?", ["Baseball", "American football", "Basketball", "Hockey"], 1],
  ["How many holes are played in a standard golf round?", ["9", "12", "18", "24"], 2],
  ["Which country invented cricket?", ["Australia", "England", "India", "South Africa"], 1],
  ["What is the national sport of Canada?", ["Hockey", "Lacrosse", "Curling", "Skiing"], 1],
  ["How many points is a touchdown worth in NFL?", ["3", "6", "7", "8"], 1],
  ["Which sport uses a net but no racket?", ["Tennis", "Volleyball", "Squash", "Badminton"], 1],
  ["Who has won the most Formula 1 world titles (as of 2023)?", ["Hamilton", "Schumacher", "Verstappen", "Prost"], 1],
  ["Which ball sport is played at the Masters?", ["Tennis", "Golf", "Cricket", "Rugby"], 1],
  ["How many periods in a standard ice hockey game?", ["2", "3", "4", "5"], 1],
  ["Which country won the 2018 FIFA World Cup?", ["Germany", "France", "Brazil", "Argentina"], 1],
  ["What is a strike in bowling?", ["5 pins", "All 10 pins", "7 pins", "Split"], 1],
  ["Who directed 'Jurassic Park'?", ["Spielberg", "Cameron", "Nolan", "Scott"], 0],
  ["Which movie features the character Iron Man?", ["DC Universe", "Marvel", "Star Wars", "Matrix"], 1],
  ["Who played Jack in 'Titanic'?", ["Pitt", "DiCaprio", "Cruise", "Depp"], 1],
  ["Which series features Hogwarts School?", ["Narnia", "Harry Potter", "Lord of the Rings", "Percy Jackson"], 1],
  ["What is the highest-grossing film franchise?", ["Star Wars", "Marvel", "Harry Potter", "Bond"], 1],
  ["Who sang 'Thriller'?", ["Prince", "Michael Jackson", "Madonna", "Elvis"], 1],
  ["Which instrument did Jimi Hendrix play?", ["Piano", "Guitar", "Drums", "Saxophone"], 1],
  ["What is the name of the lion in 'The Lion King'?", ["Mufasa", "Simba", "Scar", "Nala"], 1],
  ["Who created Mickey Mouse?", ["Warner", "Disney", "Hanna-Barbera", "Pixar"], 1],
  ["Which band performed 'Bohemian Rhapsody'?", ["Beatles", "Queen", "Led Zeppelin", "Pink Floyd"], 1],
  ["What is the wizard's name in 'The Lord of the Rings'?", ["Merlin", "Gandalf", "Dumbledore", "Saruman"], 1],
  ["Which TV show features the Iron Throne?", ["Vikings", "Game of Thrones", "Rome", "The Witcher"], 1],
  ["Who voiced Woody in 'Toy Story'?", ["Crystal", "Allen", "Hanks", "Murray"], 2],
  ["Which streaming platform made 'Stranger Things'?", ["Hulu", "Netflix", "Disney+", "HBO"], 1],
  ["What is the name of Batman's city?", ["Metropolis", "Gotham", "Star City", "Central City"], 1],
  ["Who wrote 'The Hobbit'?", ["Lewis", "Tolkien", "Rowling", "Martin"], 1],
  ["Which Disney princess has long blonde hair?", ["Ariel", "Rapunzel", "Belle", "Jasmine"], 1],
  ["What band was John Lennon in?", ["Rolling Stones", "Beatles", "Who", "Eagles"], 1],
  ["Which film features the quote 'May the Force be with you'?", ["Star Trek", "Star Wars", "Dune", "Avatar"], 1],
  ["Who played the Joker in 'The Dark Knight'?", ["Nicholson", "Ledger", "Phoenix", "Leto"], 1],
  ["Which animated film features Elsa?", ["Moana", "Frozen", "Tangled", "Brave"], 1],
  ["What is 9 squared?", ["18", "72", "81", "99"], 2],
  ["What is the square root of 144?", ["10", "11", "12", "14"], 2],
  ["How many degrees in a right angle?", ["45", "90", "180", "360"], 1],
  ["What is 1000 ÷ 10?", ["10", "100", "1000", "10000"], 1],
  ["How many millimeters in a centimeter?", ["10", "100", "1000", "5"], 0],
  ["What is 25% of 200?", ["25", "40", "50", "75"], 2],
  ["How many sides does an octagon have?", ["6", "7", "8", "9"], 2],
  ["What is 7 × 8?", ["48", "54", "56", "64"], 2],
  ["How many seconds in a minute?", ["30", "60", "100", "120"], 1],
  ["What is the value of pi (approx)?", ["2.14", "3.14", "4.14", "3.41"], 1],
  ["How many weeks in a year?", ["48", "50", "52", "54"], 2],
  ["What is 144 ÷ 12?", ["10", "11", "12", "14"], 2],
  ["How many degrees in a triangle's angles (total)?", ["90", "180", "270", "360"], 1],
  ["What is 3 to the power of 3?", ["6", "9", "27", "81"], 2],
  ["How many hours in a day?", ["12", "24", "48", "36"], 1],
  ["What is the next prime after 7?", ["8", "9", "10", "11"], 3],
  ["How many cents in a dollar?", ["10", "50", "100", "1000"], 2],
  ["What is 1/2 + 1/4?", ["1/6", "2/4", "3/4", "1"], 2],
  ["How many faces on a cube?", ["4", "6", "8", "12"], 1],
  ["What is 11 × 11?", ["111", "121", "131", "144"], 1],
  ["How many months have 31 days?", ["5", "6", "7", "8"], 2],
  ["What is the binary digit called?", ["Byte", "Bit", "Nibble", "Word"], 1],
  ["How many bytes in a kilobyte (standard)?", ["100", "512", "1000", "1024"], 3],
  ["What does CPU stand for?", ["Central Process Unit", "Central Processing Unit", "Computer Personal Unit", "Core Processing Unit"], 1],
  ["Which company makes Windows?", ["Apple", "Google", "Microsoft", "IBM"], 2],
  ["What does HTML stand for?", ["Hyper Text Markup Language", "High Tech Modern Language", "Home Tool Markup Language", "Hyper Transfer Mark Language"], 0],
  ["Which device is used to connect to Wi-Fi?", ["Router", "Printer", "Scanner", "Monitor"], 0],
  ["What does USB stand for?", ["Universal Serial Bus", "United System Bus", "Universal System Board", "Unified Serial Buffer"], 0],
  ["Which programming language is known for web browsers?", ["Python", "JavaScript", "C++", "Ruby"], 1],
  ["What is the brain of a computer?", ["RAM", "CPU", "GPU", "SSD"], 1],
  ["Which company makes the Galaxy phone?", ["Apple", "Samsung", "Nokia", "LG"], 1],
  ["What does PDF stand for?", ["Portable Document Format", "Personal Data File", "Printed Document File", "Public Data Format"], 0],
  ["Which social network was founded by Mark Zuckerberg?", ["Twitter", "Facebook", "LinkedIn", "Snapchat"], 1],
  ["What does AI stand for?", ["Automated Input", "Artificial Intelligence", "Advanced Internet", "Analog Interface"], 1],
  ["Which storage is typically faster?", ["HDD", "SSD", "CD", "Floppy"], 1],
  ["What year was the first iPhone released?", ["2005", "2007", "2009", "2010"], 1],
  ["What does VPN stand for?", ["Virtual Private Network", "Verified Public Network", "Visual Protocol Node", "Variable Port Number"], 0],
  ["Which company owns YouTube?", ["Meta", "Google", "Amazon", "Microsoft"], 1],
  ["What is the main language of Android apps (traditionally)?", ["Swift", "Kotlin/Java", "C#", "PHP"], 1],
  ["What does URL stand for?", ["Uniform Resource Locator", "Universal Reference Link", "Unified Resource Language", "User Resource Locator"], 0],
  ["Which key combination often means copy?", ["Ctrl+C", "Ctrl+V", "Ctrl+X", "Ctrl+Z"], 0],
  ["What does RAM stand for?", ["Read Access Memory", "Random Access Memory", "Rapid Application Memory", "Run Active Memory"], 1],
  ["Which browser is made by Mozilla?", ["Chrome", "Firefox", "Edge", "Safari"], 1],
];

const TARGET = 200;
const seen = new Set();
const out = [];
for (const [text, options, correctIndex] of raw) {
  if (seen.has(text)) continue;
  seen.add(text);
  out.push({ text, options, correctIndex });
  if (out.length >= TARGET) break;
}

if (out.length < TARGET) {
  console.error(`Need ${TARGET - out.length} more unique questions`);
  process.exit(1);
}

const body = out
  .map(
    (q) =>
      `  { text: ${JSON.stringify(q.text)}, options: ${JSON.stringify(q.options)}, correctIndex: ${q.correctIndex} },`,
  )
  .join("\n");

const file = `/** Trivia bank — ${TARGET} unique questions; rooms track used ids across games. */\nexport const TRIVIA_QUESTIONS = [\n${body}\n];\n`;
const dest = path.join(__dirname, "..", "triviaQuestions.js");
fs.writeFileSync(dest, file);
console.log(`Wrote ${out.length} questions to ${dest}`);
