/** Chat bubble cosmetics catalog (FB-002). Equip/render is FB-074. */

export const CHAT_BUBBLE_SAMPLE_TEXT = "WePlay";

export const CHAT_BUBBLE_CATALOG = [
  {
    id: "bubble_classic",
    name: "Classic",
    type: "chat_bubble",
    previewClass: "chat-bubble-preview--classic",
    source: "coin",
    cost: 120,
    tag: null,
    bg: "#f3e8ff",
    emoji: "💬",
  },
  {
    id: "bubble_star",
    name: "Starlight",
    type: "chat_bubble",
    previewClass: "chat-bubble-preview--star",
    source: "coin",
    cost: 150,
    tag: null,
    bg: "#fef9c3",
    emoji: "⭐",
  },
  {
    id: "bubble_heart",
    name: "Heart",
    type: "chat_bubble",
    previewClass: "chat-bubble-preview--heart",
    source: "coin",
    cost: 180,
    tag: null,
    bg: "#fce7f3",
    emoji: "💗",
  },
  {
    id: "bubble_ocean",
    name: "Ocean",
    type: "chat_bubble",
    previewClass: "chat-bubble-preview--ocean",
    source: "coin",
    cost: 250,
    tag: null,
    bg: "#e0f2fe",
    emoji: "🌊",
  },
  {
    id: "bubble_sunset",
    name: "Sunset",
    type: "chat_bubble",
    previewClass: "chat-bubble-preview--sunset",
    source: "coin",
    cost: 300,
    tag: null,
    bg: "#ffedd5",
    emoji: "🌅",
  },
  {
    id: "bubble_neon",
    name: "Neon",
    type: "chat_bubble",
    previewClass: "chat-bubble-preview--neon",
    source: "coin",
    cost: 420,
    tag: null,
    bg: "#ecfccb",
    emoji: "✨",
  },
  {
    id: "bubble_vip3",
    name: "VIP Aura",
    type: "chat_bubble",
    previewClass: "chat-bubble-preview--vip3",
    source: "vip",
    minVip: 3,
    tag: "From VIP 3",
    bg: "#fef3c7",
    emoji: "👑",
  },
  {
    id: "bubble_vip6",
    name: "Royal",
    type: "chat_bubble",
    previewClass: "chat-bubble-preview--vip6",
    source: "vip",
    minVip: 6,
    tag: "From VIP 6",
    bg: "#fde68a",
    emoji: "💎",
  },
  {
    id: "bubble_vip8",
    name: "Emperor",
    type: "chat_bubble",
    previewClass: "chat-bubble-preview--vip8",
    source: "vip",
    minVip: 8,
    tag: "From VIP 8",
    bg: "#fcd34d",
    emoji: "🏆",
  },
  {
    id: "bubble_family",
    name: "Family Crest",
    type: "chat_bubble",
    previewClass: "chat-bubble-preview--family",
    source: "family",
    requiresClan: true,
    tag: "From Family",
    bg: "#dbeafe",
    emoji: "🏠",
  },
  {
    id: "bubble_family_gold",
    name: "Family Gold",
    type: "chat_bubble",
    previewClass: "chat-bubble-preview--family-gold",
    source: "family",
    requiresClan: true,
    tag: "From Family",
    bg: "#fef3c7",
    emoji: "🛡️",
  },
];

export function inventoryPayloadFromBubble(item) {
  return {
    id: item.id,
    name: item.name,
    type: item.type,
    emoji: item.emoji,
    category: "Chat Bubble",
    tag: item.tag,
    bg: item.bg,
    previewClass: item.previewClass,
    source: item.source,
    cost: item.cost ?? null,
    minVip: item.minVip ?? null,
    requiresClan: item.requiresClan ?? false,
  };
}
